### ISSUE TITLE
[SkullUtils] - Allow disabling "NULLABILITY_RECORD_UPDATE"

### ISSUE THREAD

**Issue by datatags** [CryptoMorin/XSeries#251]
**Description**
Wondering if you would consider adding a feature to not use the "nullability record update" features. The reason is that ViaBackwards doesn't correctly translate skulls that use it ([issue](https://github.com/ViaVersion/ViaBackwards/issues/691)), and since the skulls generated without those features work equally as well for newer clients, it would be handy to be able to turn that off. (Or just have it off all the time, doesn't really matter as long as the end result is achieved!)

I understand if you would prefer not to do anything about it since the bug is actually with ViaBackwards, just thought I'd ask since it should be an easy change if you decide to do it.

**Comment by CryptoMorin** [comment]
Like you said, it is a very simple change yes. But me changing this does not fix the source of the issue that is ViaBackwards, and other plugins doing this in other ways is still going to be an issue for anyone using ViaBackwards. So I'd prefer to wait for them to fix it instead.
Btw I really appreciate that you actually took your time to identify the root of the issue rather than assuming it's a SkullUtils bug!
