### ISSUE TITLE
[XSkull] - Non stackable items

### ISSUE THREAD

**Issue by Condordito** [CryptoMorin/XSeries#277]
**Description**

Previously, XSkull used to remove the timestamp from profiles to avoid having different NBT tags after restarts. This is no longer the case, and it additionally adds a property with the utility's version (Plugins using different versions may also conflict with this behavior, resulting in some items not being stackable)

Note: This is also the default behavior with the server implementation, which keeps the timestamps as well

![DEMO](https://github.com/CryptoMorin/XSeries/assets/48872538/34b06751-4896-4a7e-89cb-2ff86d6ca4d5)

**Comment by CryptoMorin** [comment]
I mean, it's the default behavior yes. It's not really a bug.
Also other possibilities that can conflict with this:
- Future versions of the API/cache might add additional properties that conflict with previous versions.
- The players might change a part of their skin, let's say a texture on their hand but not the head which looks the same in terms of items/blocks but wouldn't be stackable because of the changed URL.

Those are both rare cases, but I think it'd be better to add a method to `ProfileInstruction#removeExtraData(boolean)` that defaults to false instead that handles this on its own?
I'm not sure how it'd affect blocks, or if it keeps the entire GameProfile object. We could also add a separate method `ProfileInstruction#stackable(boolean)` that adds extra properties to ensure its not stackable if false, or call removeExtraData if true.

**Comment by Condordito** [comment]
Yeah, sure, this is more like a feature request for a special use case

> Those are both rare cases, but I think it'd be better to add a method to `ProfileInstruction#removeExtraData(boolean)` that defaults to false and handles this on its own.

> We could also add a separate method `ProfileInstruction#stackable(boolean)` that adds extra properties to ensure it's not stackable if false, or call `removeExtraData` if true.

I also think it'll be better to have those methods instead. These cases are rare, but it requires an API or user change, while this behavior currently happens on re-fetching

> I'm not sure how it'd affect blocks, or if it keeps the entire GameProfile object.

I haven't tested a lot with blocks either, but I've seen they have a separate loading cache that expires every 10 minutes after access

**Comment by CryptoMorin** [comment]
Check the latest commit. I decided to take a more abstract approach.
Example:
```java
XSkull.of(item).profile(Profileable.username("Notch").transform(ProfileTransformer.stackable())).apply();
```

Thoughts?

**Comment by Condordito** [comment]
Awesome thank you. I'll close it as completed now
