### ISSUE TITLE
Question about XSkull & Discord

### ISSUE THREAD

**Issue by Splitrox** [CryptoMorin/XSeries#289]
Hello @CryptoMorin, where can I find more about what is XSkull and how it can be applied? Also do you have a discord server or something similar?

**Comment by CryptoMorin** [comment]
I don't have a Discord server. The spigot thread is the only place.

As for XSkull. It's mostly explained in the JavaDocs. It can apply textures to items and blocks using different values.
```java
XSkull.of(item/block).profile(Profileable.of(configValueString)).apply();
```
You can check Profileable for different ways to set a texture.

It also replaces Skull#setOwner methods from Spigot API because those methods don't properly handle edge cases, specially support for offline servers.

**Comment by CryptoMorin** [comment]
```java
XSkull.of(item/block).profile(Profileable.username("")).apply();
```
