### ISSUE TITLE
[XMaterial] - Filled Map #0 resolves into MAP instead of FILLED_MAP in legacy versions

### ISSUE THREAD

**Issue by LOOHP** [CryptoMorin/XSeries#91]
**Description**
Filled Maps in 1.8 resolves into MAP (which is for empty maps) instead of FILLED_MAP

In version 1.8.9:
Opens a map in the game
XMaterial material = XMaterial.matchXMaterial(playerItemStackInHand);
material -> XMaterial.MAP (which should be XMaterial.FILLED_MAP)

**Version**
This bug occurs on 1.8.9 but it works fine on 1.16.4

**Comment by CryptoMorin** [comment]
This only happens to **Map #0* which really can't be fixed since both this and EMPTY_MAP have a data value of 0 and there isn't a way to detect whether it's a filled map or not.

The only way is to check if the item meta is an instance of [MapMeta](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/inventory/meta/MapMeta.html) which is not something that XMaterial is supposed to do. Adds an extra check only to support a single material.

**Comment by LOOHP** [comment]
Ah alright, then I'll do the check myself. Thank you.
