### ISSUE TITLE
[XEnchantment] - java.lang.ClassNotFoundException: org.bukkit.NamespacedKey

### ISSUE THREAD

**Issue by GabrielBlink32** [CryptoMorin/XSeries#93]
**Description**
Error ClassNotFoundException in 1.8.8 server with XEnchantment Library simply this

Pastebin with the error: [Click here](https://pastebin.com/MN8M7TaK)
Pastebin with the latest.log: [Click here](https://pastebin.com/Q0H675cK)
Pastebin with my code: [Click here](https://pastebin.com/6aa2vFGw)

**Version**
I'm using paperspigot (MC 1.8.8) and my maven library version is:

`		
               <dependency>
			<groupId>com.github.cryptomorin</groupId>
			<artifactId>XSeries</artifactId>
			<version>7.8.0</version>
		</dependency>
`

**Comment by CryptoMorin** [comment]
I'm unable to reproduce this using the following code in the latest 1.8,8
```java
Player player = event.getPlayer();
ItemStack item = XMaterial.DIAMOND_SWORD.parseItem();
item.addUnsafeEnchantment(XEnchantment.DURABILITY.parseEnchantment(), 1);
player.getInventory().addItem(item);
```

And it makes perfect sense because:
https://github.com/CryptoMorin/XSeries/blob/3a56fda765454925d8f7d68e8c8623c1d3e6c74d/src/main/java/com/cryptomorin/xseries/XEnchantment.java#L366

Please make sure you're using the latest utility version.

**Comment by GabrielBlink32** [comment]
WTF "Please make sure you're using the latest utility version." ???

I already posted my maven dependency...

**Comment by CryptoMorin** [comment]
What do you expect me to do if I can't reproduce it? You can even see the code for yourself. It catches `ClassNotFoundException` that you're getting. So it probably on your side.
It doesn't matter what maven repo you use. Because you just copy pasted the class. It's not even shaded.
`com.atlasplugins.mysterybox.api.XEnchantment`

**Comment by GabrielBlink32** [comment]
I shaded the class and i decompiled after compiled the jar but it is so weird because the XEnchantment.class really have the catch block with the ClassNotFoundException but still keep it going throwing the error.

**Comment by CryptoMorin** [comment]
Yeah, I'm not really sure either, but something's suspicious about your class loader.
The error itself looks abnormal in general. If you found the solution, tell me too.
